namespace Obstacles
{
    public enum ObstacleType
    {
        brownStone,
        brownStone1,
        brownStone2,
        brownStone3,
        brownStone4,
        brownStone5,
        brownStone6,
        brownStone7,
        brownStone8,
        brownStone9,
        brownStone10,
        brownStone11,
        brownStone12,
        brownStone13,
        brownStone14,
        brownStone15,
        brownStone16,
        brownStone17,
        brownStone18,
        brownStone19,
        brownStone20,
        brownStone21,
        brownStone22,
        brownStone23,
        brownStone24,
    }
}